/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExpertiseRouteImport } from './routes/expertise'
import { Route as InvestorsPartnersRouteImport } from './routes/investors-partners'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WhyUsRouteImport } from './routes/why-us'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin/messages'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin/staff'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin/team'
import { Route as AuthenticatedAdminCmsFaqsRouteImport } from './routes/_authenticated/admin/cms.faqs'
import { Route as AuthenticatedAdminCmsPagesRouteImport } from './routes/_authenticated/admin/cms.pages'
import { Route as AuthenticatedAdminCmsProjectsRouteImport } from './routes/_authenticated/admin/cms.projects'
import { Route as AuthenticatedAdminCmsServicesRouteImport } from './routes/_authenticated/admin/cms.services'
import { Route as AuthenticatedAdminCmsSlidesRouteImport } from './routes/_authenticated/admin/cms.slides'
import { Route as AuthenticatedAdminCmsTestimonialsRouteImport } from './routes/_authenticated/admin/cms.testimonials'
import { Route as AuthenticatedAdminEnquiriesContactRouteImport } from './routes/_authenticated/admin/enquiries.contact'
import { Route as AuthenticatedAdminEnquiriesInvestorsRouteImport } from './routes/_authenticated/admin/enquiries.investors'
import { Route as AuthenticatedAdminEnquiriesPartnersRouteImport } from './routes/_authenticated/admin/enquiries.partners'
import { Route as AuthenticatedAdminEnquiriesQuotesRouteImport } from './routes/_authenticated/admin/enquiries.quotes'
import { Route as AuthenticatedAdminEnquiriesSubscribersRouteImport } from './routes/_authenticated/admin/enquiries.subscribers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertiseRoute = ExpertiseRouteImport.update({
  id: '/expertise',
  path: '/expertise',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsPartnersRoute = InvestorsPartnersRouteImport.update({
  id: '/investors-partners',
  path: '/investors-partners',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyUsRoute = WhyUsRouteImport.update({
  id: '/why-us',
  path: '/why-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCmsFaqsRoute =
  AuthenticatedAdminCmsFaqsRouteImport.update({
    id: '/cms/faqs',
    path: '/cms/faqs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCmsPagesRoute =
  AuthenticatedAdminCmsPagesRouteImport.update({
    id: '/cms/pages',
    path: '/cms/pages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCmsProjectsRoute =
  AuthenticatedAdminCmsProjectsRouteImport.update({
    id: '/cms/projects',
    path: '/cms/projects',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCmsServicesRoute =
  AuthenticatedAdminCmsServicesRouteImport.update({
    id: '/cms/services',
    path: '/cms/services',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCmsSlidesRoute =
  AuthenticatedAdminCmsSlidesRouteImport.update({
    id: '/cms/slides',
    path: '/cms/slides',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCmsTestimonialsRoute =
  AuthenticatedAdminCmsTestimonialsRouteImport.update({
    id: '/cms/testimonials',
    path: '/cms/testimonials',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEnquiriesContactRoute =
  AuthenticatedAdminEnquiriesContactRouteImport.update({
    id: '/enquiries/contact',
    path: '/enquiries/contact',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEnquiriesInvestorsRoute =
  AuthenticatedAdminEnquiriesInvestorsRouteImport.update({
    id: '/enquiries/investors',
    path: '/enquiries/investors',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEnquiriesPartnersRoute =
  AuthenticatedAdminEnquiriesPartnersRouteImport.update({
    id: '/enquiries/partners',
    path: '/enquiries/partners',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEnquiriesQuotesRoute =
  AuthenticatedAdminEnquiriesQuotesRouteImport.update({
    id: '/enquiries/quotes',
    path: '/enquiries/quotes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEnquiriesSubscribersRoute =
  AuthenticatedAdminEnquiriesSubscribersRouteImport.update({
    id: '/enquiries/subscribers',
    path: '/enquiries/subscribers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/expertise': typeof ExpertiseRoute
  '/investors-partners': typeof InvestorsPartnersRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/quote': typeof QuoteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/why-us': typeof WhyUsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/services/$slug': typeof ServicesSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/cms/faqs': typeof AuthenticatedAdminCmsFaqsRoute
  '/admin/cms/pages': typeof AuthenticatedAdminCmsPagesRoute
  '/admin/cms/projects': typeof AuthenticatedAdminCmsProjectsRoute
  '/admin/cms/services': typeof AuthenticatedAdminCmsServicesRoute
  '/admin/cms/slides': typeof AuthenticatedAdminCmsSlidesRoute
  '/admin/cms/testimonials': typeof AuthenticatedAdminCmsTestimonialsRoute
  '/admin/enquiries/contact': typeof AuthenticatedAdminEnquiriesContactRoute
  '/admin/enquiries/investors': typeof AuthenticatedAdminEnquiriesInvestorsRoute
  '/admin/enquiries/partners': typeof AuthenticatedAdminEnquiriesPartnersRoute
  '/admin/enquiries/quotes': typeof AuthenticatedAdminEnquiriesQuotesRoute
  '/admin/enquiries/subscribers': typeof AuthenticatedAdminEnquiriesSubscribersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/expertise': typeof ExpertiseRoute
  '/investors-partners': typeof InvestorsPartnersRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/quote': typeof QuoteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/why-us': typeof WhyUsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services': typeof ServicesIndexRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/cms/faqs': typeof AuthenticatedAdminCmsFaqsRoute
  '/admin/cms/pages': typeof AuthenticatedAdminCmsPagesRoute
  '/admin/cms/projects': typeof AuthenticatedAdminCmsProjectsRoute
  '/admin/cms/services': typeof AuthenticatedAdminCmsServicesRoute
  '/admin/cms/slides': typeof AuthenticatedAdminCmsSlidesRoute
  '/admin/cms/testimonials': typeof AuthenticatedAdminCmsTestimonialsRoute
  '/admin/enquiries/contact': typeof AuthenticatedAdminEnquiriesContactRoute
  '/admin/enquiries/investors': typeof AuthenticatedAdminEnquiriesInvestorsRoute
  '/admin/enquiries/partners': typeof AuthenticatedAdminEnquiriesPartnersRoute
  '/admin/enquiries/quotes': typeof AuthenticatedAdminEnquiriesQuotesRoute
  '/admin/enquiries/subscribers': typeof AuthenticatedAdminEnquiriesSubscribersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/expertise': typeof ExpertiseRoute
  '/investors-partners': typeof InvestorsPartnersRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/quote': typeof QuoteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/why-us': typeof WhyUsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/services/$slug': typeof ServicesSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/cms/faqs': typeof AuthenticatedAdminCmsFaqsRoute
  '/_authenticated/admin/cms/pages': typeof AuthenticatedAdminCmsPagesRoute
  '/_authenticated/admin/cms/projects': typeof AuthenticatedAdminCmsProjectsRoute
  '/_authenticated/admin/cms/services': typeof AuthenticatedAdminCmsServicesRoute
  '/_authenticated/admin/cms/slides': typeof AuthenticatedAdminCmsSlidesRoute
  '/_authenticated/admin/cms/testimonials': typeof AuthenticatedAdminCmsTestimonialsRoute
  '/_authenticated/admin/enquiries/contact': typeof AuthenticatedAdminEnquiriesContactRoute
  '/_authenticated/admin/enquiries/investors': typeof AuthenticatedAdminEnquiriesInvestorsRoute
  '/_authenticated/admin/enquiries/partners': typeof AuthenticatedAdminEnquiriesPartnersRoute
  '/_authenticated/admin/enquiries/quotes': typeof AuthenticatedAdminEnquiriesQuotesRoute
  '/_authenticated/admin/enquiries/subscribers': typeof AuthenticatedAdminEnquiriesSubscribersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/expertise'
    | '/investors-partners'
    | '/login'
    | '/projects'
    | '/quote'
    | '/sitemap.xml'
    | '/why-us'
    | '/admin'
    | '/services/$slug'
    | '/services/'
    | '/admin/messages'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/team'
    | '/admin/'
    | '/admin/cms/faqs'
    | '/admin/cms/pages'
    | '/admin/cms/projects'
    | '/admin/cms/services'
    | '/admin/cms/slides'
    | '/admin/cms/testimonials'
    | '/admin/enquiries/contact'
    | '/admin/enquiries/investors'
    | '/admin/enquiries/partners'
    | '/admin/enquiries/quotes'
    | '/admin/enquiries/subscribers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/expertise'
    | '/investors-partners'
    | '/login'
    | '/projects'
    | '/quote'
    | '/sitemap.xml'
    | '/why-us'
    | '/services/$slug'
    | '/services'
    | '/admin/messages'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/team'
    | '/admin'
    | '/admin/cms/faqs'
    | '/admin/cms/pages'
    | '/admin/cms/projects'
    | '/admin/cms/services'
    | '/admin/cms/slides'
    | '/admin/cms/testimonials'
    | '/admin/enquiries/contact'
    | '/admin/enquiries/investors'
    | '/admin/enquiries/partners'
    | '/admin/enquiries/quotes'
    | '/admin/enquiries/subscribers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/expertise'
    | '/investors-partners'
    | '/login'
    | '/projects'
    | '/quote'
    | '/sitemap.xml'
    | '/why-us'
    | '/_authenticated/admin'
    | '/services/$slug'
    | '/services/'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/team'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/cms/faqs'
    | '/_authenticated/admin/cms/pages'
    | '/_authenticated/admin/cms/projects'
    | '/_authenticated/admin/cms/services'
    | '/_authenticated/admin/cms/slides'
    | '/_authenticated/admin/cms/testimonials'
    | '/_authenticated/admin/enquiries/contact'
    | '/_authenticated/admin/enquiries/investors'
    | '/_authenticated/admin/enquiries/partners'
    | '/_authenticated/admin/enquiries/quotes'
    | '/_authenticated/admin/enquiries/subscribers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ExpertiseRoute: typeof ExpertiseRoute
  InvestorsPartnersRoute: typeof InvestorsPartnersRoute
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRoute
  QuoteRoute: typeof QuoteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WhyUsRoute: typeof WhyUsRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertise': {
      id: '/expertise'
      path: '/expertise'
      fullPath: '/expertise'
      preLoaderRoute: typeof ExpertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors-partners': {
      id: '/investors-partners'
      path: '/investors-partners'
      fullPath: '/investors-partners'
      preLoaderRoute: typeof InvestorsPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-us': {
      id: '/why-us'
      path: '/why-us'
      fullPath: '/why-us'
      preLoaderRoute: typeof WhyUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cms/faqs': {
      id: '/_authenticated/admin/cms/faqs'
      path: '/cms/faqs'
      fullPath: '/admin/cms/faqs'
      preLoaderRoute: typeof AuthenticatedAdminCmsFaqsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cms/pages': {
      id: '/_authenticated/admin/cms/pages'
      path: '/cms/pages'
      fullPath: '/admin/cms/pages'
      preLoaderRoute: typeof AuthenticatedAdminCmsPagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cms/projects': {
      id: '/_authenticated/admin/cms/projects'
      path: '/cms/projects'
      fullPath: '/admin/cms/projects'
      preLoaderRoute: typeof AuthenticatedAdminCmsProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cms/services': {
      id: '/_authenticated/admin/cms/services'
      path: '/cms/services'
      fullPath: '/admin/cms/services'
      preLoaderRoute: typeof AuthenticatedAdminCmsServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cms/slides': {
      id: '/_authenticated/admin/cms/slides'
      path: '/cms/slides'
      fullPath: '/admin/cms/slides'
      preLoaderRoute: typeof AuthenticatedAdminCmsSlidesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cms/testimonials': {
      id: '/_authenticated/admin/cms/testimonials'
      path: '/cms/testimonials'
      fullPath: '/admin/cms/testimonials'
      preLoaderRoute: typeof AuthenticatedAdminCmsTestimonialsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/enquiries/contact': {
      id: '/_authenticated/admin/enquiries/contact'
      path: '/enquiries/contact'
      fullPath: '/admin/enquiries/contact'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesContactRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/enquiries/investors': {
      id: '/_authenticated/admin/enquiries/investors'
      path: '/enquiries/investors'
      fullPath: '/admin/enquiries/investors'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesInvestorsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/enquiries/partners': {
      id: '/_authenticated/admin/enquiries/partners'
      path: '/enquiries/partners'
      fullPath: '/admin/enquiries/partners'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesPartnersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/enquiries/quotes': {
      id: '/_authenticated/admin/enquiries/quotes'
      path: '/enquiries/quotes'
      fullPath: '/admin/enquiries/quotes'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesQuotesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/enquiries/subscribers': {
      id: '/_authenticated/admin/enquiries/subscribers'
      path: '/enquiries/subscribers'
      fullPath: '/admin/enquiries/subscribers'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesSubscribersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCmsFaqsRoute: typeof AuthenticatedAdminCmsFaqsRoute
  AuthenticatedAdminCmsPagesRoute: typeof AuthenticatedAdminCmsPagesRoute
  AuthenticatedAdminCmsProjectsRoute: typeof AuthenticatedAdminCmsProjectsRoute
  AuthenticatedAdminCmsServicesRoute: typeof AuthenticatedAdminCmsServicesRoute
  AuthenticatedAdminCmsSlidesRoute: typeof AuthenticatedAdminCmsSlidesRoute
  AuthenticatedAdminCmsTestimonialsRoute: typeof AuthenticatedAdminCmsTestimonialsRoute
  AuthenticatedAdminEnquiriesContactRoute: typeof AuthenticatedAdminEnquiriesContactRoute
  AuthenticatedAdminEnquiriesInvestorsRoute: typeof AuthenticatedAdminEnquiriesInvestorsRoute
  AuthenticatedAdminEnquiriesPartnersRoute: typeof AuthenticatedAdminEnquiriesPartnersRoute
  AuthenticatedAdminEnquiriesQuotesRoute: typeof AuthenticatedAdminEnquiriesQuotesRoute
  AuthenticatedAdminEnquiriesSubscribersRoute: typeof AuthenticatedAdminEnquiriesSubscribersRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
    AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminCmsFaqsRoute: AuthenticatedAdminCmsFaqsRoute,
    AuthenticatedAdminCmsPagesRoute: AuthenticatedAdminCmsPagesRoute,
    AuthenticatedAdminCmsProjectsRoute: AuthenticatedAdminCmsProjectsRoute,
    AuthenticatedAdminCmsServicesRoute: AuthenticatedAdminCmsServicesRoute,
    AuthenticatedAdminCmsSlidesRoute: AuthenticatedAdminCmsSlidesRoute,
    AuthenticatedAdminCmsTestimonialsRoute:
      AuthenticatedAdminCmsTestimonialsRoute,
    AuthenticatedAdminEnquiriesContactRoute:
      AuthenticatedAdminEnquiriesContactRoute,
    AuthenticatedAdminEnquiriesInvestorsRoute:
      AuthenticatedAdminEnquiriesInvestorsRoute,
    AuthenticatedAdminEnquiriesPartnersRoute:
      AuthenticatedAdminEnquiriesPartnersRoute,
    AuthenticatedAdminEnquiriesQuotesRoute:
      AuthenticatedAdminEnquiriesQuotesRoute,
    AuthenticatedAdminEnquiriesSubscribersRoute:
      AuthenticatedAdminEnquiriesSubscribersRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ExpertiseRoute: ExpertiseRoute,
  InvestorsPartnersRoute: InvestorsPartnersRoute,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRoute,
  QuoteRoute: QuoteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WhyUsRoute: WhyUsRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
