/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EnquiryRouteImport } from './routes/enquiry'
import { Route as ExpertiseRouteImport } from './routes/expertise'
import { Route as InvestorsPartnersRouteImport } from './routes/investors-partners'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WhyUsRouteImport } from './routes/why-us'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as CustomerDashboardRouteImport } from './routes/customer.dashboard'
import { Route as CustomerLoginRouteImport } from './routes/customer.login'
import { Route as CustomerSignupRouteImport } from './routes/customer.signup'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin/messages'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin/staff'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin/team'
import { Route as AuthenticatedAdminCmsFaqsRouteImport } from './routes/_authenticated/admin/cms.faqs'
import { Route as AuthenticatedAdminCmsPagesRouteImport } from './routes/_authenticated/admin/cms.pages'
import { Route as AuthenticatedAdminCmsProjectsRouteImport } from './routes/_authenticated/admin/cms.projects'
import { Route as AuthenticatedAdminCmsServicesRouteImport } from './routes/_authenticated/admin/cms.services'
import { Route as AuthenticatedAdminCmsSlidesRouteImport } from './routes/_authenticated/admin/cms.slides'
import { Route as AuthenticatedAdminCmsTestimonialsRouteImport } from './routes/_authenticated/admin/cms.testimonials'
import { Route as AuthenticatedAdminEcommerceBrandsRouteImport } from './routes/_authenticated/admin/ecommerce.brands'
import { Route as AuthenticatedAdminEcommerceCouponsRouteImport } from './routes/_authenticated/admin/ecommerce.coupons'
import { Route as AuthenticatedAdminEcommerceCreditNotesRouteImport } from './routes/_authenticated/admin/ecommerce.credit-notes'
import { Route as AuthenticatedAdminEcommerceCustomersRouteImport } from './routes/_authenticated/admin/ecommerce.customers'
import { Route as AuthenticatedAdminEcommerceEnquiriesRouteImport } from './routes/_authenticated/admin/ecommerce.enquiries'
import { Route as AuthenticatedAdminEcommerceInventoryRouteImport } from './routes/_authenticated/admin/ecommerce.inventory'
import { Route as AuthenticatedAdminEcommerceOrdersRouteImport } from './routes/_authenticated/admin/ecommerce.orders'
import { Route as AuthenticatedAdminEcommercePackagesRouteImport } from './routes/_authenticated/admin/ecommerce.packages'
import { Route as AuthenticatedAdminEcommerceProductsRouteImport } from './routes/_authenticated/admin/ecommerce.products'
import { Route as AuthenticatedAdminEcommerceShippingRouteImport } from './routes/_authenticated/admin/ecommerce.shipping'
import { Route as AuthenticatedAdminEnquiriesContactRouteImport } from './routes/_authenticated/admin/enquiries.contact'
import { Route as AuthenticatedAdminEnquiriesInvestorsRouteImport } from './routes/_authenticated/admin/enquiries.investors'
import { Route as AuthenticatedAdminEnquiriesPartnersRouteImport } from './routes/_authenticated/admin/enquiries.partners'
import { Route as AuthenticatedAdminEnquiriesQuotesRouteImport } from './routes/_authenticated/admin/enquiries.quotes'
import { Route as AuthenticatedAdminEnquiriesSubscribersRouteImport } from './routes/_authenticated/admin/enquiries.subscribers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiryRoute = EnquiryRouteImport.update({
  id: '/enquiry',
  path: '/enquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertiseRoute = ExpertiseRouteImport.update({
  id: '/expertise',
  path: '/expertise',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsPartnersRoute = InvestorsPartnersRouteImport.update({
  id: '/investors-partners',
  path: '/investors-partners',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyUsRoute = WhyUsRouteImport.update({
  id: '/why-us',
  path: '/why-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/customer/dashboard',
  path: '/customer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerLoginRoute = CustomerLoginRouteImport.update({
  id: '/customer/login',
  path: '/customer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSignupRoute = CustomerSignupRouteImport.update({
  id: '/customer/signup',
  path: '/customer/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCmsFaqsRoute =
  AuthenticatedAdminCmsFaqsRouteImport.update({
    id: '/cms/faqs',
    path: '/cms/faqs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCmsPagesRoute =
  AuthenticatedAdminCmsPagesRouteImport.update({
    id: '/cms/pages',
    path: '/cms/pages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCmsProjectsRoute =
  AuthenticatedAdminCmsProjectsRouteImport.update({
    id: '/cms/projects',
    path: '/cms/projects',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCmsServicesRoute =
  AuthenticatedAdminCmsServicesRouteImport.update({
    id: '/cms/services',
    path: '/cms/services',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCmsSlidesRoute =
  AuthenticatedAdminCmsSlidesRouteImport.update({
    id: '/cms/slides',
    path: '/cms/slides',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCmsTestimonialsRoute =
  AuthenticatedAdminCmsTestimonialsRouteImport.update({
    id: '/cms/testimonials',
    path: '/cms/testimonials',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEcommerceBrandsRoute =
  AuthenticatedAdminEcommerceBrandsRouteImport.update({
    id: '/ecommerce/brands',
    path: '/ecommerce/brands',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEcommerceCouponsRoute =
  AuthenticatedAdminEcommerceCouponsRouteImport.update({
    id: '/ecommerce/coupons',
    path: '/ecommerce/coupons',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEcommerceCreditNotesRoute =
  AuthenticatedAdminEcommerceCreditNotesRouteImport.update({
    id: '/ecommerce/credit-notes',
    path: '/ecommerce/credit-notes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEcommerceCustomersRoute =
  AuthenticatedAdminEcommerceCustomersRouteImport.update({
    id: '/ecommerce/customers',
    path: '/ecommerce/customers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEcommerceEnquiriesRoute =
  AuthenticatedAdminEcommerceEnquiriesRouteImport.update({
    id: '/ecommerce/enquiries',
    path: '/ecommerce/enquiries',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEcommerceInventoryRoute =
  AuthenticatedAdminEcommerceInventoryRouteImport.update({
    id: '/ecommerce/inventory',
    path: '/ecommerce/inventory',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEcommerceOrdersRoute =
  AuthenticatedAdminEcommerceOrdersRouteImport.update({
    id: '/ecommerce/orders',
    path: '/ecommerce/orders',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEcommercePackagesRoute =
  AuthenticatedAdminEcommercePackagesRouteImport.update({
    id: '/ecommerce/packages',
    path: '/ecommerce/packages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEcommerceProductsRoute =
  AuthenticatedAdminEcommerceProductsRouteImport.update({
    id: '/ecommerce/products',
    path: '/ecommerce/products',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEcommerceShippingRoute =
  AuthenticatedAdminEcommerceShippingRouteImport.update({
    id: '/ecommerce/shipping',
    path: '/ecommerce/shipping',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEnquiriesContactRoute =
  AuthenticatedAdminEnquiriesContactRouteImport.update({
    id: '/enquiries/contact',
    path: '/enquiries/contact',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEnquiriesInvestorsRoute =
  AuthenticatedAdminEnquiriesInvestorsRouteImport.update({
    id: '/enquiries/investors',
    path: '/enquiries/investors',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEnquiriesPartnersRoute =
  AuthenticatedAdminEnquiriesPartnersRouteImport.update({
    id: '/enquiries/partners',
    path: '/enquiries/partners',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEnquiriesQuotesRoute =
  AuthenticatedAdminEnquiriesQuotesRouteImport.update({
    id: '/enquiries/quotes',
    path: '/enquiries/quotes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEnquiriesSubscribersRoute =
  AuthenticatedAdminEnquiriesSubscribersRouteImport.update({
    id: '/enquiries/subscribers',
    path: '/enquiries/subscribers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/enquiry': typeof EnquiryRoute
  '/expertise': typeof ExpertiseRoute
  '/investors-partners': typeof InvestorsPartnersRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/products': typeof ProductsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/quote': typeof QuoteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/why-us': typeof WhyUsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/signup': typeof CustomerSignupRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/cms/faqs': typeof AuthenticatedAdminCmsFaqsRoute
  '/admin/cms/pages': typeof AuthenticatedAdminCmsPagesRoute
  '/admin/cms/projects': typeof AuthenticatedAdminCmsProjectsRoute
  '/admin/cms/services': typeof AuthenticatedAdminCmsServicesRoute
  '/admin/cms/slides': typeof AuthenticatedAdminCmsSlidesRoute
  '/admin/cms/testimonials': typeof AuthenticatedAdminCmsTestimonialsRoute
  '/admin/ecommerce/brands': typeof AuthenticatedAdminEcommerceBrandsRoute
  '/admin/ecommerce/coupons': typeof AuthenticatedAdminEcommerceCouponsRoute
  '/admin/ecommerce/credit-notes': typeof AuthenticatedAdminEcommerceCreditNotesRoute
  '/admin/ecommerce/customers': typeof AuthenticatedAdminEcommerceCustomersRoute
  '/admin/ecommerce/enquiries': typeof AuthenticatedAdminEcommerceEnquiriesRoute
  '/admin/ecommerce/inventory': typeof AuthenticatedAdminEcommerceInventoryRoute
  '/admin/ecommerce/orders': typeof AuthenticatedAdminEcommerceOrdersRoute
  '/admin/ecommerce/packages': typeof AuthenticatedAdminEcommercePackagesRoute
  '/admin/ecommerce/products': typeof AuthenticatedAdminEcommerceProductsRoute
  '/admin/ecommerce/shipping': typeof AuthenticatedAdminEcommerceShippingRoute
  '/admin/enquiries/contact': typeof AuthenticatedAdminEnquiriesContactRoute
  '/admin/enquiries/investors': typeof AuthenticatedAdminEnquiriesInvestorsRoute
  '/admin/enquiries/partners': typeof AuthenticatedAdminEnquiriesPartnersRoute
  '/admin/enquiries/quotes': typeof AuthenticatedAdminEnquiriesQuotesRoute
  '/admin/enquiries/subscribers': typeof AuthenticatedAdminEnquiriesSubscribersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/enquiry': typeof EnquiryRoute
  '/expertise': typeof ExpertiseRoute
  '/investors-partners': typeof InvestorsPartnersRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/products': typeof ProductsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/quote': typeof QuoteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/why-us': typeof WhyUsRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/signup': typeof CustomerSignupRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services': typeof ServicesIndexRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/cms/faqs': typeof AuthenticatedAdminCmsFaqsRoute
  '/admin/cms/pages': typeof AuthenticatedAdminCmsPagesRoute
  '/admin/cms/projects': typeof AuthenticatedAdminCmsProjectsRoute
  '/admin/cms/services': typeof AuthenticatedAdminCmsServicesRoute
  '/admin/cms/slides': typeof AuthenticatedAdminCmsSlidesRoute
  '/admin/cms/testimonials': typeof AuthenticatedAdminCmsTestimonialsRoute
  '/admin/ecommerce/brands': typeof AuthenticatedAdminEcommerceBrandsRoute
  '/admin/ecommerce/coupons': typeof AuthenticatedAdminEcommerceCouponsRoute
  '/admin/ecommerce/credit-notes': typeof AuthenticatedAdminEcommerceCreditNotesRoute
  '/admin/ecommerce/customers': typeof AuthenticatedAdminEcommerceCustomersRoute
  '/admin/ecommerce/enquiries': typeof AuthenticatedAdminEcommerceEnquiriesRoute
  '/admin/ecommerce/inventory': typeof AuthenticatedAdminEcommerceInventoryRoute
  '/admin/ecommerce/orders': typeof AuthenticatedAdminEcommerceOrdersRoute
  '/admin/ecommerce/packages': typeof AuthenticatedAdminEcommercePackagesRoute
  '/admin/ecommerce/products': typeof AuthenticatedAdminEcommerceProductsRoute
  '/admin/ecommerce/shipping': typeof AuthenticatedAdminEcommerceShippingRoute
  '/admin/enquiries/contact': typeof AuthenticatedAdminEnquiriesContactRoute
  '/admin/enquiries/investors': typeof AuthenticatedAdminEnquiriesInvestorsRoute
  '/admin/enquiries/partners': typeof AuthenticatedAdminEnquiriesPartnersRoute
  '/admin/enquiries/quotes': typeof AuthenticatedAdminEnquiriesQuotesRoute
  '/admin/enquiries/subscribers': typeof AuthenticatedAdminEnquiriesSubscribersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/enquiry': typeof EnquiryRoute
  '/expertise': typeof ExpertiseRoute
  '/investors-partners': typeof InvestorsPartnersRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/products': typeof ProductsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/quote': typeof QuoteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/why-us': typeof WhyUsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/signup': typeof CustomerSignupRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/cms/faqs': typeof AuthenticatedAdminCmsFaqsRoute
  '/_authenticated/admin/cms/pages': typeof AuthenticatedAdminCmsPagesRoute
  '/_authenticated/admin/cms/projects': typeof AuthenticatedAdminCmsProjectsRoute
  '/_authenticated/admin/cms/services': typeof AuthenticatedAdminCmsServicesRoute
  '/_authenticated/admin/cms/slides': typeof AuthenticatedAdminCmsSlidesRoute
  '/_authenticated/admin/cms/testimonials': typeof AuthenticatedAdminCmsTestimonialsRoute
  '/_authenticated/admin/ecommerce/brands': typeof AuthenticatedAdminEcommerceBrandsRoute
  '/_authenticated/admin/ecommerce/coupons': typeof AuthenticatedAdminEcommerceCouponsRoute
  '/_authenticated/admin/ecommerce/credit-notes': typeof AuthenticatedAdminEcommerceCreditNotesRoute
  '/_authenticated/admin/ecommerce/customers': typeof AuthenticatedAdminEcommerceCustomersRoute
  '/_authenticated/admin/ecommerce/enquiries': typeof AuthenticatedAdminEcommerceEnquiriesRoute
  '/_authenticated/admin/ecommerce/inventory': typeof AuthenticatedAdminEcommerceInventoryRoute
  '/_authenticated/admin/ecommerce/orders': typeof AuthenticatedAdminEcommerceOrdersRoute
  '/_authenticated/admin/ecommerce/packages': typeof AuthenticatedAdminEcommercePackagesRoute
  '/_authenticated/admin/ecommerce/products': typeof AuthenticatedAdminEcommerceProductsRoute
  '/_authenticated/admin/ecommerce/shipping': typeof AuthenticatedAdminEcommerceShippingRoute
  '/_authenticated/admin/enquiries/contact': typeof AuthenticatedAdminEnquiriesContactRoute
  '/_authenticated/admin/enquiries/investors': typeof AuthenticatedAdminEnquiriesInvestorsRoute
  '/_authenticated/admin/enquiries/partners': typeof AuthenticatedAdminEnquiriesPartnersRoute
  '/_authenticated/admin/enquiries/quotes': typeof AuthenticatedAdminEnquiriesQuotesRoute
  '/_authenticated/admin/enquiries/subscribers': typeof AuthenticatedAdminEnquiriesSubscribersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/enquiry'
    | '/expertise'
    | '/investors-partners'
    | '/login'
    | '/packages'
    | '/products'
    | '/projects'
    | '/quote'
    | '/sitemap.xml'
    | '/why-us'
    | '/admin'
    | '/customer/dashboard'
    | '/customer/login'
    | '/customer/signup'
    | '/products/$slug'
    | '/services/$slug'
    | '/services/'
    | '/admin/messages'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/team'
    | '/admin/'
    | '/admin/cms/faqs'
    | '/admin/cms/pages'
    | '/admin/cms/projects'
    | '/admin/cms/services'
    | '/admin/cms/slides'
    | '/admin/cms/testimonials'
    | '/admin/ecommerce/brands'
    | '/admin/ecommerce/coupons'
    | '/admin/ecommerce/credit-notes'
    | '/admin/ecommerce/customers'
    | '/admin/ecommerce/enquiries'
    | '/admin/ecommerce/inventory'
    | '/admin/ecommerce/orders'
    | '/admin/ecommerce/packages'
    | '/admin/ecommerce/products'
    | '/admin/ecommerce/shipping'
    | '/admin/enquiries/contact'
    | '/admin/enquiries/investors'
    | '/admin/enquiries/partners'
    | '/admin/enquiries/quotes'
    | '/admin/enquiries/subscribers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/enquiry'
    | '/expertise'
    | '/investors-partners'
    | '/login'
    | '/packages'
    | '/products'
    | '/projects'
    | '/quote'
    | '/sitemap.xml'
    | '/why-us'
    | '/customer/dashboard'
    | '/customer/login'
    | '/customer/signup'
    | '/products/$slug'
    | '/services/$slug'
    | '/services'
    | '/admin/messages'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/team'
    | '/admin'
    | '/admin/cms/faqs'
    | '/admin/cms/pages'
    | '/admin/cms/projects'
    | '/admin/cms/services'
    | '/admin/cms/slides'
    | '/admin/cms/testimonials'
    | '/admin/ecommerce/brands'
    | '/admin/ecommerce/coupons'
    | '/admin/ecommerce/credit-notes'
    | '/admin/ecommerce/customers'
    | '/admin/ecommerce/enquiries'
    | '/admin/ecommerce/inventory'
    | '/admin/ecommerce/orders'
    | '/admin/ecommerce/packages'
    | '/admin/ecommerce/products'
    | '/admin/ecommerce/shipping'
    | '/admin/enquiries/contact'
    | '/admin/enquiries/investors'
    | '/admin/enquiries/partners'
    | '/admin/enquiries/quotes'
    | '/admin/enquiries/subscribers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/enquiry'
    | '/expertise'
    | '/investors-partners'
    | '/login'
    | '/packages'
    | '/products'
    | '/projects'
    | '/quote'
    | '/sitemap.xml'
    | '/why-us'
    | '/_authenticated/admin'
    | '/customer/dashboard'
    | '/customer/login'
    | '/customer/signup'
    | '/products/$slug'
    | '/services/$slug'
    | '/services/'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/team'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/cms/faqs'
    | '/_authenticated/admin/cms/pages'
    | '/_authenticated/admin/cms/projects'
    | '/_authenticated/admin/cms/services'
    | '/_authenticated/admin/cms/slides'
    | '/_authenticated/admin/cms/testimonials'
    | '/_authenticated/admin/ecommerce/brands'
    | '/_authenticated/admin/ecommerce/coupons'
    | '/_authenticated/admin/ecommerce/credit-notes'
    | '/_authenticated/admin/ecommerce/customers'
    | '/_authenticated/admin/ecommerce/enquiries'
    | '/_authenticated/admin/ecommerce/inventory'
    | '/_authenticated/admin/ecommerce/orders'
    | '/_authenticated/admin/ecommerce/packages'
    | '/_authenticated/admin/ecommerce/products'
    | '/_authenticated/admin/ecommerce/shipping'
    | '/_authenticated/admin/enquiries/contact'
    | '/_authenticated/admin/enquiries/investors'
    | '/_authenticated/admin/enquiries/partners'
    | '/_authenticated/admin/enquiries/quotes'
    | '/_authenticated/admin/enquiries/subscribers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  EnquiryRoute: typeof EnquiryRoute
  ExpertiseRoute: typeof ExpertiseRoute
  InvestorsPartnersRoute: typeof InvestorsPartnersRoute
  LoginRoute: typeof LoginRoute
  PackagesRoute: typeof PackagesRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
  QuoteRoute: typeof QuoteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WhyUsRoute: typeof WhyUsRoute
  CustomerDashboardRoute: typeof CustomerDashboardRoute
  CustomerLoginRoute: typeof CustomerLoginRoute
  CustomerSignupRoute: typeof CustomerSignupRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiry': {
      id: '/enquiry'
      path: '/enquiry'
      fullPath: '/enquiry'
      preLoaderRoute: typeof EnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertise': {
      id: '/expertise'
      path: '/expertise'
      fullPath: '/expertise'
      preLoaderRoute: typeof ExpertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors-partners': {
      id: '/investors-partners'
      path: '/investors-partners'
      fullPath: '/investors-partners'
      preLoaderRoute: typeof InvestorsPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-us': {
      id: '/why-us'
      path: '/why-us'
      fullPath: '/why-us'
      preLoaderRoute: typeof WhyUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/customer/dashboard': {
      id: '/customer/dashboard'
      path: '/customer/dashboard'
      fullPath: '/customer/dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/login': {
      id: '/customer/login'
      path: '/customer/login'
      fullPath: '/customer/login'
      preLoaderRoute: typeof CustomerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/signup': {
      id: '/customer/signup'
      path: '/customer/signup'
      fullPath: '/customer/signup'
      preLoaderRoute: typeof CustomerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cms/faqs': {
      id: '/_authenticated/admin/cms/faqs'
      path: '/cms/faqs'
      fullPath: '/admin/cms/faqs'
      preLoaderRoute: typeof AuthenticatedAdminCmsFaqsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cms/pages': {
      id: '/_authenticated/admin/cms/pages'
      path: '/cms/pages'
      fullPath: '/admin/cms/pages'
      preLoaderRoute: typeof AuthenticatedAdminCmsPagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cms/projects': {
      id: '/_authenticated/admin/cms/projects'
      path: '/cms/projects'
      fullPath: '/admin/cms/projects'
      preLoaderRoute: typeof AuthenticatedAdminCmsProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cms/services': {
      id: '/_authenticated/admin/cms/services'
      path: '/cms/services'
      fullPath: '/admin/cms/services'
      preLoaderRoute: typeof AuthenticatedAdminCmsServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cms/slides': {
      id: '/_authenticated/admin/cms/slides'
      path: '/cms/slides'
      fullPath: '/admin/cms/slides'
      preLoaderRoute: typeof AuthenticatedAdminCmsSlidesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cms/testimonials': {
      id: '/_authenticated/admin/cms/testimonials'
      path: '/cms/testimonials'
      fullPath: '/admin/cms/testimonials'
      preLoaderRoute: typeof AuthenticatedAdminCmsTestimonialsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ecommerce/brands': {
      id: '/_authenticated/admin/ecommerce/brands'
      path: '/ecommerce/brands'
      fullPath: '/admin/ecommerce/brands'
      preLoaderRoute: typeof AuthenticatedAdminEcommerceBrandsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ecommerce/coupons': {
      id: '/_authenticated/admin/ecommerce/coupons'
      path: '/ecommerce/coupons'
      fullPath: '/admin/ecommerce/coupons'
      preLoaderRoute: typeof AuthenticatedAdminEcommerceCouponsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ecommerce/credit-notes': {
      id: '/_authenticated/admin/ecommerce/credit-notes'
      path: '/ecommerce/credit-notes'
      fullPath: '/admin/ecommerce/credit-notes'
      preLoaderRoute: typeof AuthenticatedAdminEcommerceCreditNotesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ecommerce/customers': {
      id: '/_authenticated/admin/ecommerce/customers'
      path: '/ecommerce/customers'
      fullPath: '/admin/ecommerce/customers'
      preLoaderRoute: typeof AuthenticatedAdminEcommerceCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ecommerce/enquiries': {
      id: '/_authenticated/admin/ecommerce/enquiries'
      path: '/ecommerce/enquiries'
      fullPath: '/admin/ecommerce/enquiries'
      preLoaderRoute: typeof AuthenticatedAdminEcommerceEnquiriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ecommerce/inventory': {
      id: '/_authenticated/admin/ecommerce/inventory'
      path: '/ecommerce/inventory'
      fullPath: '/admin/ecommerce/inventory'
      preLoaderRoute: typeof AuthenticatedAdminEcommerceInventoryRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ecommerce/orders': {
      id: '/_authenticated/admin/ecommerce/orders'
      path: '/ecommerce/orders'
      fullPath: '/admin/ecommerce/orders'
      preLoaderRoute: typeof AuthenticatedAdminEcommerceOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ecommerce/packages': {
      id: '/_authenticated/admin/ecommerce/packages'
      path: '/ecommerce/packages'
      fullPath: '/admin/ecommerce/packages'
      preLoaderRoute: typeof AuthenticatedAdminEcommercePackagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ecommerce/products': {
      id: '/_authenticated/admin/ecommerce/products'
      path: '/ecommerce/products'
      fullPath: '/admin/ecommerce/products'
      preLoaderRoute: typeof AuthenticatedAdminEcommerceProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ecommerce/shipping': {
      id: '/_authenticated/admin/ecommerce/shipping'
      path: '/ecommerce/shipping'
      fullPath: '/admin/ecommerce/shipping'
      preLoaderRoute: typeof AuthenticatedAdminEcommerceShippingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/enquiries/contact': {
      id: '/_authenticated/admin/enquiries/contact'
      path: '/enquiries/contact'
      fullPath: '/admin/enquiries/contact'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesContactRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/enquiries/investors': {
      id: '/_authenticated/admin/enquiries/investors'
      path: '/enquiries/investors'
      fullPath: '/admin/enquiries/investors'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesInvestorsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/enquiries/partners': {
      id: '/_authenticated/admin/enquiries/partners'
      path: '/enquiries/partners'
      fullPath: '/admin/enquiries/partners'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesPartnersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/enquiries/quotes': {
      id: '/_authenticated/admin/enquiries/quotes'
      path: '/enquiries/quotes'
      fullPath: '/admin/enquiries/quotes'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesQuotesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/enquiries/subscribers': {
      id: '/_authenticated/admin/enquiries/subscribers'
      path: '/enquiries/subscribers'
      fullPath: '/admin/enquiries/subscribers'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesSubscribersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCmsFaqsRoute: typeof AuthenticatedAdminCmsFaqsRoute
  AuthenticatedAdminCmsPagesRoute: typeof AuthenticatedAdminCmsPagesRoute
  AuthenticatedAdminCmsProjectsRoute: typeof AuthenticatedAdminCmsProjectsRoute
  AuthenticatedAdminCmsServicesRoute: typeof AuthenticatedAdminCmsServicesRoute
  AuthenticatedAdminCmsSlidesRoute: typeof AuthenticatedAdminCmsSlidesRoute
  AuthenticatedAdminCmsTestimonialsRoute: typeof AuthenticatedAdminCmsTestimonialsRoute
  AuthenticatedAdminEcommerceBrandsRoute: typeof AuthenticatedAdminEcommerceBrandsRoute
  AuthenticatedAdminEcommerceCouponsRoute: typeof AuthenticatedAdminEcommerceCouponsRoute
  AuthenticatedAdminEcommerceCreditNotesRoute: typeof AuthenticatedAdminEcommerceCreditNotesRoute
  AuthenticatedAdminEcommerceCustomersRoute: typeof AuthenticatedAdminEcommerceCustomersRoute
  AuthenticatedAdminEcommerceEnquiriesRoute: typeof AuthenticatedAdminEcommerceEnquiriesRoute
  AuthenticatedAdminEcommerceInventoryRoute: typeof AuthenticatedAdminEcommerceInventoryRoute
  AuthenticatedAdminEcommerceOrdersRoute: typeof AuthenticatedAdminEcommerceOrdersRoute
  AuthenticatedAdminEcommercePackagesRoute: typeof AuthenticatedAdminEcommercePackagesRoute
  AuthenticatedAdminEcommerceProductsRoute: typeof AuthenticatedAdminEcommerceProductsRoute
  AuthenticatedAdminEcommerceShippingRoute: typeof AuthenticatedAdminEcommerceShippingRoute
  AuthenticatedAdminEnquiriesContactRoute: typeof AuthenticatedAdminEnquiriesContactRoute
  AuthenticatedAdminEnquiriesInvestorsRoute: typeof AuthenticatedAdminEnquiriesInvestorsRoute
  AuthenticatedAdminEnquiriesPartnersRoute: typeof AuthenticatedAdminEnquiriesPartnersRoute
  AuthenticatedAdminEnquiriesQuotesRoute: typeof AuthenticatedAdminEnquiriesQuotesRoute
  AuthenticatedAdminEnquiriesSubscribersRoute: typeof AuthenticatedAdminEnquiriesSubscribersRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
    AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminCmsFaqsRoute: AuthenticatedAdminCmsFaqsRoute,
    AuthenticatedAdminCmsPagesRoute: AuthenticatedAdminCmsPagesRoute,
    AuthenticatedAdminCmsProjectsRoute: AuthenticatedAdminCmsProjectsRoute,
    AuthenticatedAdminCmsServicesRoute: AuthenticatedAdminCmsServicesRoute,
    AuthenticatedAdminCmsSlidesRoute: AuthenticatedAdminCmsSlidesRoute,
    AuthenticatedAdminCmsTestimonialsRoute:
      AuthenticatedAdminCmsTestimonialsRoute,
    AuthenticatedAdminEcommerceBrandsRoute:
      AuthenticatedAdminEcommerceBrandsRoute,
    AuthenticatedAdminEcommerceCouponsRoute:
      AuthenticatedAdminEcommerceCouponsRoute,
    AuthenticatedAdminEcommerceCreditNotesRoute:
      AuthenticatedAdminEcommerceCreditNotesRoute,
    AuthenticatedAdminEcommerceCustomersRoute:
      AuthenticatedAdminEcommerceCustomersRoute,
    AuthenticatedAdminEcommerceEnquiriesRoute:
      AuthenticatedAdminEcommerceEnquiriesRoute,
    AuthenticatedAdminEcommerceInventoryRoute:
      AuthenticatedAdminEcommerceInventoryRoute,
    AuthenticatedAdminEcommerceOrdersRoute:
      AuthenticatedAdminEcommerceOrdersRoute,
    AuthenticatedAdminEcommercePackagesRoute:
      AuthenticatedAdminEcommercePackagesRoute,
    AuthenticatedAdminEcommerceProductsRoute:
      AuthenticatedAdminEcommerceProductsRoute,
    AuthenticatedAdminEcommerceShippingRoute:
      AuthenticatedAdminEcommerceShippingRoute,
    AuthenticatedAdminEnquiriesContactRoute:
      AuthenticatedAdminEnquiriesContactRoute,
    AuthenticatedAdminEnquiriesInvestorsRoute:
      AuthenticatedAdminEnquiriesInvestorsRoute,
    AuthenticatedAdminEnquiriesPartnersRoute:
      AuthenticatedAdminEnquiriesPartnersRoute,
    AuthenticatedAdminEnquiriesQuotesRoute:
      AuthenticatedAdminEnquiriesQuotesRoute,
    AuthenticatedAdminEnquiriesSubscribersRoute:
      AuthenticatedAdminEnquiriesSubscribersRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  EnquiryRoute: EnquiryRoute,
  ExpertiseRoute: ExpertiseRoute,
  InvestorsPartnersRoute: InvestorsPartnersRoute,
  LoginRoute: LoginRoute,
  PackagesRoute: PackagesRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
  QuoteRoute: QuoteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WhyUsRoute: WhyUsRoute,
  CustomerDashboardRoute: CustomerDashboardRoute,
  CustomerLoginRoute: CustomerLoginRoute,
  CustomerSignupRoute: CustomerSignupRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
